version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: dev
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-minor-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"