---
name: 'build images'
# See https://itnext.io/building-multi-cpu-architecture-docker-images-for-arm-and-x86-3-building-in-github-action-ci-a382feab5af9

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker-images:
    name: Build Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Package Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build & Push Docker image for web UI
        run: docker buildx build -t ghcr.io/${{ github.repository_owner }}/linkwarden:${GITHUB_SHA} -f ./Dockerfile.prod --push --platform=linux/arm64,linux/amd64 .
      - name: Build & Push Docker image for API
        run: docker buildx build -t ghcr.io/${{ github.repository_owner }}/linkwarden-api:${GITHUB_SHA} -f ./api/Dockerfile --push --platform=linux/arm64,linux/amd64 ./api
      - name: Login to Docker Hub
        env:
          DH_TOKEN: ${{ secrets.DOCKER_HUB_PASSWORD }}
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${DH_TOKEN}
      - name: Re-tag & Push Docker Image to Docker Hub Web
        run: |
          # make config.json avaiable to regclient in docker container
          chmod +r $HOME/.docker/config.json
          # Run regclient in docker image
          docker container run --rm --net host \
            -v regctl-conf:/home/appuser/.regctl/ \
            -v $HOME/.docker/config.json:/home/appuser/.docker/config.json \
            regclient/regctl:v0.3.9 image copy ghcr.io/${{ github.repository_owner }}/linkwarden:${GITHUB_SHA} docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/linkwarden:latest
      - name: Re-tag & Push Docker Image to Docker Hub API
        run: |
          # make config.json avaiable to regclient in docker container
          chmod +r $HOME/.docker/config.json
          # Run regclient in docker image
          docker container run --rm --net host \
            -v regctl-conf:/home/appuser/.regctl/ \
            -v $HOME/.docker/config.json:/home/appuser/.docker/config.json \
            regclient/regctl:v0.3.9 image copy ghcr.io/${{ github.repository_owner }}/linkwarden-api:${GITHUB_SHA} docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/linkwarden-api:latest
