name: Manage i18n pull requests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  rewrite-author:
    if: github.event.pull_request.head.ref == 'i18n'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full history of the i18n branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Give up early if the latest commit is already from LinkwardenBot
        run: |
          if [ "$(git show -s --format='%an')" = 'LinkwardenBot' ]; then
            echo "Already rewritten – skipping."
            exit 0
          fi

      - name: Set bot identity in local Git config
        run: |
          git config user.name  "LinkwardenBot"
          git config user.email "bot@linkwarden.app"

      - name: Install git-filter-repo (safer & faster than filter-branch)
        run: |
          pip install --quiet git-filter-repo

      - name: Capture origin URL
        id: save_remote
        run: |
          echo "REMOTE_URL=$(git remote get-url origin)" >> $GITHUB_OUTPUT

      - name: Rewrite every commit’s author/committer
        run: |
          git filter-repo \
            --name-callback  'return b"LinkwardenBot"' \
            --email-callback 'return b"bot@linkwarden.app"' \
            --commit-callback '
                commit.committer_name  = b"LinkwardenBot"
                commit.committer_email = b"bot@linkwarden.app"
            '

      - name: Restore origin and recreate tracking branch
        run: |
          git remote add origin "${{ steps.save_remote.outputs.REMOTE_URL }}"
          git fetch origin i18n --depth=1 --no-tags

      - name: Push rewritten history
        run: git push --force-with-lease origin HEAD:i18n